import = [
	"/home/vaeep/.config/alacritty/themes/themes/solarized_dark.toml"
]

[shell]
program = "/bin/bash"

[window]
padding = { x = 5 , y = 5}
opacity = 1

[font]
normal = { family = "Iosevka NF", style = "Regular" }
size =  20
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 800
unfocused_hollow = true

[mouse]
hide_when_typing = true
