#import = ["/home/vaeep/dotfiles/alacritty/themes/themes/nord.toml"]

[shell]
program = "/bin/zsh"

[window]
padding = { x = 0 , y = 0}
opacity = 1

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Medium" }
size = 32
offset = { x = 0, y = 2 }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 800
unfocused_hollow = true

[mouse]
hide_when_typing = true

# Default colors
[colors.primary]
background = '#121212'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#333333'
green   = '#95A99F'
yellow  = '#FFCC22'
blue    = '#96A6C8'
magenta = '#888888'
cyan    = '#BBBBBB'
white   = '#EBEEEE'

# Bright colors
[colors.bright]
black   = '#282828'
red     = '#333333'
green   = '#95A99F'
yellow  = '#FFCC22'
blue    = '#96A6C8'
magenta = '#888888'
cyan    = '#BBBBBB'
white   = '#EBEEEE'
